### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by santiagoworkana** [Linch1/wiinsta-instagram-manager#2]
**Describe the bug**
I just run the bot, it opns my account, goes to my profile and then the next refresh is not found
![image](https://user-images.githubusercontent.com/33036105/88968630-f8826580-d285-11ea-93b9-1fdd56566c76.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Wiinsta version: 

**Additional context**

**Comment by Linch1** [comment]
Try to go in the logs page and check the messages, maybe is just a typo in the page field

**Comment by santiagoworkana** [comment]
There is no bug.
I was adding the @ to the account name... without it it just work
